var data = [
  {
    img:"../JUEGO_1/images/CristianoRonaldo.png",
    name: "Cristiano Ronaldo",
    ritmo: 91,
    tiro: 95,
    pase: 84,
    regate: 92,
    defensa: 34,
    fisico: 82,
  },
{
    img:"../JUEGO_1/images/Messi.png",
    name: "Messi",
    ritmo: 96,
    tiro: 97,
    pase: 98,
    regate: 99,
    defensa: 45,
    fisico: 81,
  },
{
    img:"../JUEGO_1/images/Griezmann.png",
    name: "Griezmann",
    ritmo: 89,
    tiro: 89,
    pase: 84,
    regate: 91,
    defensa: 35,
    fisico: 74,
  },
{
    img:"../JUEGO_1/images/SergioRamos.png",
    name: "Sergio Ramos",
    ritmo: 86,
    tiro: 79,
    pase: 88,
    regate: 89,
    defensa: 98,
    fisico: 96,
  },
{
    img:"../JUEGO_1/images/Pique.png",
    name: "Pique",
    ritmo: 65,
    tiro: 61,
    pase: 69,
    regate: 66,
    defensa: 86,
    fisico: 76,
  },
{
    img:"../JUEGO_1/images/Godin.png",
    name: "Godin",
    ritmo: 65,
    tiro: 48,
    pase: 65,
    regate: 64,
    defensa: 88,
    fisico: 78,
  },
]
